# Generated by Django 5.0.7 on 2024-07-23 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 23, 16, 9, 54, 592901, tzinfo=datetime.timezone.utc)),
        ),
    ]
